// To join the webring, submit a form at debate-webring.com/join
// Maintainers: approved submissions are added here automatically via Airtable automation
const SITES = [
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "Hart House Debating Club, University of Toronto",
    location: "Toronto, Canada",
    description: "Writing about competitive debate, policy, and ideas.",
  },
  {
    name: "Priya Mehta",
    url: "https://priyamehta.substack.com",
    type: "newsletter",
    club: "Oxford Union, University of Oxford",
    location: "Oxford, UK",
    description: "Parliamentary debate coaching and theory, sent weekly.",
  },
  {
    name: "Soren Albrecht",
    url: "https://sorenalbrecht.com",
    type: "website",
    club: "IDEA Germany, TU Berlin",
    location: "Berlin, Germany",
    description: "Thoughts on debate education and civic rhetoric.",
  },
  {
    name: "Mia Tanaka",
    url: "https://youtube.com/@miatanaka",
    type: "youtube",
    club: "Waseda Debating Society",
    location: "Tokyo, Japan",
    description: "World Schools prep videos and adjudication breakdowns.",
  },
  {
    name: "Kofi Asante",
    url: "https://kofiasante.com",
    type: "website",
    club: "UCT Debating Union, University of Cape Town",
    location: "Cape Town, South Africa",
    description: "Pan-African debate circuit news and commentary.",
  },
  {
    name: "Lena Fischer",
    url: "https://lenafischer.de",
    type: "website",
    club: "Debattierclub Wien",
    location: "Vienna, Austria",
    description: "European debate formats, philosophy, and occasional fiction.",
  },
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "Hart House Debating Club, University of Toronto",
    location: "Toronto, Canada",
    description: "Writing about competitive debate, policy, and ideas.",
  },
  {
    name: "Priya Mehta",
    url: "https://priyamehta.substack.com",
    type: "newsletter",
    club: "Oxford Union, University of Oxford",
    location: "Oxford, UK",
    description: "Parliamentary debate coaching and theory, sent weekly.",
  },
  {
    name: "Soren Albrecht",
    url: "https://sorenalbrecht.com",
    type: "website",
    club: "IDEA Germany, TU Berlin",
    location: "Berlin, Germany",
    description: "Thoughts on debate education and civic rhetoric.",
  },
  {
    name: "Mia Tanaka",
    url: "https://youtube.com/@miatanaka",
    type: "youtube",
    club: "Waseda Debating Society",
    location: "Tokyo, Japan",
    description: "World Schools prep videos and adjudication breakdowns.",
  },
  {
    name: "Kofi Asante",
    url: "https://kofiasante.com",
    type: "website",
    club: "UCT Debating Union, University of Cape Town",
    location: "Cape Town, South Africa",
    description: "Pan-African debate circuit news and commentary.",
  },
  {
    name: "Lena Fischer",
    url: "https://lenafischer.de",
    type: "website",
    club: "Debattierclub Wien",
    location: "Vienna, Austria",
    description: "European debate formats, philosophy, and occasional fiction.",
  },
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "Hart House Debating Club, University of Toronto",
    location: "Toronto, Canada",
    description: "Writing about competitive debate, policy, and ideas.",
  },
  {
    name: "Priya Mehta",
    url: "https://priyamehta.substack.com",
    type: "newsletter",
    club: "Oxford Union, University of Oxford",
    location: "Oxford, UK",
    description: "Parliamentary debate coaching and theory, sent weekly.",
  },
  {
    name: "Soren Albrecht",
    url: "https://sorenalbrecht.com",
    type: "website",
    club: "IDEA Germany, TU Berlin",
    location: "Berlin, Germany",
    description: "Thoughts on debate education and civic rhetoric.",
  },
  {
    name: "Mia Tanaka",
    url: "https://youtube.com/@miatanaka",
    type: "youtube",
    club: "Waseda Debating Society",
    location: "Tokyo, Japan",
    description: "World Schools prep videos and adjudication breakdowns.",
  },
  {
    name: "Kofi Asante",
    url: "https://kofiasante.com",
    type: "website",
    club: "UCT Debating Union, University of Cape Town",
    location: "Cape Town, South Africa",
    description: "Pan-African debate circuit news and commentary.",
  },
  {
    name: "Lena Fischer",
    url: "https://lenafischer.de",
    type: "website",
    club: "Debattierclub Wien",
    location: "Vienna, Austria",
    description: "European debate formats, philosophy, and occasional fiction.",
  },
  {name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "Hart House Debating Club, University of Toronto",
    location: "Toronto, Canada",
    description: "Writing about competitive debate, policy, and ideas.",
  },
  {
    name: "Priya Mehta",
    url: "https://priyamehta.substack.com",
    type: "newsletter",
    club: "Oxford Union, University of Oxford",
    location: "Oxford, UK",
    description: "Parliamentary debate coaching and theory, sent weekly.",
  },
  {
    name: "Soren Albrecht",
    url: "https://sorenalbrecht.com",
    type: "website",
    club: "IDEA Germany, TU Berlin",
    location: "Berlin, Germany",
    description: "Thoughts on debate education and civic rhetoric.",
  },
  {
    name: "Mia Tanaka",
    url: "https://youtube.com/@miatanaka",
    type: "youtube",
    club: "Waseda Debating Society",
    location: "Tokyo, Japan",
    description: "World Schools prep videos and adjudication breakdowns.",
  },
  {
    name: "Kofi Asante",
    url: "https://kofiasante.com",
    type: "website",
    club: "UCT Debating Union, University of Cape Town",
    location: "Cape Town, South Africa",
    description: "Pan-African debate circuit news and commentary.",
  },
  {
    name: "Lena Fischer",
    url: "https://lenafischer.de",
    type: "website",
    club: "Debattierclub Wien",
    location: "Vienna, Austria",
    description: "European debate formats, philosophy, and occasional fiction.",
  },
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "Hart House Debating Club, University of Toronto",
    location: "Toronto, Canada",
    description: "Writing about competitive debate, policy, and ideas.",
  },
  {
    name: "Priya Mehta",
    url: "https://priyamehta.substack.com",
    type: "newsletter",
    club: "Oxford Union, University of Oxford",
    location: "Oxford, UK",
    description: "Parliamentary debate coaching and theory, sent weekly.",
  },
  {
    name: "Soren Albrecht",
    url: "https://sorenalbrecht.com",
    type: "website",
    club: "IDEA Germany, TU Berlin",
    location: "Berlin, Germany",
    description: "Thoughts on debate education and civic rhetoric.",
  },
  {
    name: "Mia Tanaka",
    url: "https://youtube.com/@miatanaka",
    type: "youtube",
    club: "Waseda Debating Society",
    location: "Tokyo, Japan",
    description: "World Schools prep videos and adjudication breakdowns.",
  },
  {
    name: "Kofi Asante",
    url: "https://kofiasante.com",
    type: "website",
    club: "UCT Debating Union, University of Cape Town",
    location: "Cape Town, South Africa",
    description: "Pan-African debate circuit news and commentary.",
  },
  {
    name: "Lena Fischer",
    url: "https://lenafischer.de",
    type: "website",
    club: "Debattierclub Wien",
    location: "Vienna, Austria",
    description: "European debate formats, philosophy, and occasional fiction.",
  },
];
