// To join the webring, submit a form at debate-webring.com/join
// Maintainers: approved submissions are added here automatically via Google Apps Script.
const SITES = [
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "University of Waterloo Debating Society",
    location: "Waterloo, Canada",
    lat: 43.4643,
    lng: -80.5204,
    color: "#3BD2EF",
    description: "Personal website: cybersecurity + debate + fun stuff.",
  },
  {
    name: "The Dispatch",
    url: "https://thedispatch.substack.com",
    type: "newsletter",
    club: "Oxford Union",
    location: "Oxford, United Kingdom",
    lat: 51.7520,
    lng: -1.2577,
    color: "#FFB63A",
    description: "Weekly takes on policy, philosophy, and competitive debate from a BP circuit veteran.",
  },
  {
    name: "Rebuttal Hour",
    url: "https://rebuttalhour.fm",
    type: "podcast",
    club: "Yale Debate Association",
    location: "New Haven, United States",
    lat: 41.3083,
    lng: -72.9279,
    color: "#EF3B71",
    description: "Long-form conversations with debaters, coaches, and adjudicators from across the circuit.",
  },
  {
    name: "Case Files",
    url: "https://casefiles.beehiiv.com",
    type: "newsletter",
    club: "Sydney Debating Union",
    location: "Sydney, Australia",
    lat: -33.8688,
    lng: 151.2093,
    color: "#FFB63A",
    description: "Motion breakdowns, case structures, and prep notes for BP and Worlds-style debate.",
  },
  {
    name: "Priya Nair",
    url: "https://priyanair.in",
    type: "website",
    club: "NLSIU Debate Club",
    location: "Bangalore, India",
    lat: 12.9716,
    lng: 77.5946,
    color: "#EF3B71",
    description: "Writing on law, rhetoric, and what competitive debate taught me about argument.",
  },
  {
    name: "The Flow",
    url: "https://youtube.com/@theflowdebate",
    type: "youtube",
    club: "McGill Debate Union",
    location: "Montreal, Canada",
    lat: 45.5017,
    lng: -73.5673,
    color: "#EF3B71",
    description: "Rounds, tutorials, and coaching breakdowns for new and experienced debaters.",
  },
  {
    name: "Finn Larsen",
    url: "https://finnlarsen.dk",
    type: "website",
    club: "Copenhagen Debate Society",
    location: "Copenhagen, Denmark",
    lat: 55.6761,
    lng: 12.5683,
    color: "#3BD2EF",
    description: "Essays on European politics and the craft of persuasion.",
  },
  {
    name: "Threshold",
    url: "https://threshold.ghost.io",
    type: "newsletter",
    club: "Trinity College Dublin Philosophical Society",
    location: "Dublin, Ireland",
    lat: 53.3498,
    lng: -6.2603,
    color: "#FFB63A",
    description: "At the edge of policy and philosophy — one motion per issue, argued both ways.",
  },
  {
    name: "Aiko Tanaka",
    url: "https://aikotanaka.jp",
    type: "website",
    club: "Waseda University Debating Society",
    location: "Tokyo, Japan",
    lat: 35.6762,
    lng: 139.6503,
    color: "#3BD2EF",
    description: "Notes on Asian BP circuit, judging philosophy, and life after competitive debate.",
  },
  {
    name: "Hard to Rebut",
    url: "https://hardtorebut.com",
    type: "podcast",
    club: "University of Cape Town Debating Union",
    location: "Cape Town, South Africa",
    lat: -33.9249,
    lng: 18.4241,
    color: "#FFB63A",
    description: "A podcast about ideas that are genuinely difficult to argue against.",
  },
];
