// To join the webring, submit a form at debate-webring.com/join
// Maintainers: approved submissions are added here automatically via Airtable automation
const SITES = [
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "University of Waterloo Debating Society",
    location: "Waterloo, Canada",
    description: "Personal website: cybersecurity + debate + fun stuff.",
  },
  {
    name: "The Dispatch",
    url: "https://thedispatch.substack.com",
    type: "newsletter",
    club: "Oxford Union",
    location: "Oxford, United Kingdom",
    description: "Weekly takes on policy, philosophy, and competitive debate from a BP circuit veteran.",
  },
  {
    name: "Rebuttal Hour",
    url: "https://rebuttalhour.fm",
    type: "podcast",
    club: "Yale Debate Association",
    location: "New Haven, United States",
    description: "Long-form conversations with debaters, coaches, and adjudicators from across the circuit.",
  },
  {
    name: "Case Files",
    url: "https://casefiles.beehiiv.com",
    type: "newsletter",
    club: "Sydney Debating Union",
    location: "Sydney, Australia",
    description: "Motion breakdowns, case structures, and prep notes for BP and Worlds-style debate.",
  },
  {
    name: "Priya Nair",
    url: "https://priyanair.in",
    type: "website",
    club: "NLSIU Debate Club",
    location: "Bangalore, India",
    description: "Writing on law, rhetoric, and what competitive debate taught me about argument.",
  },
  {
    name: "The Flow",
    url: "https://youtube.com/@theflowdebate",
    type: "youtube",
    club: "McGill Debate Union",
    location: "Montreal, Canada",
    description: "Rounds, tutorials, and coaching breakdowns for new and experienced debaters.",
  },
  {
    name: "Finn Larsen",
    url: "https://finnlarsen.dk",
    type: "website",
    club: "Copenhagen Debate Society",
    location: "Copenhagen, Denmark",
    description: "Essays on European politics and the craft of persuasion.",
  },
  {
    name: "Threshold",
    url: "https://threshold.ghost.io",
    type: "newsletter",
    club: "Trinity College Dublin Philosophical Society",
    location: "Dublin, Ireland",
    description: "At the edge of policy and philosophy — one motion per issue, argued both ways.",
  },
  {
    name: "Aiko Tanaka",
    url: "https://aikotanaka.jp",
    type: "website",
    club: "Waseda University Debating Society",
    location: "Tokyo, Japan",
    description: "Notes on Asian BP circuit, judging philosophy, and life after competitive debate.",
  },
  {
    name: "Hard to Rebut",
    url: "https://hardtorebut.com",
    type: "podcast",
    club: "University of Cape Town Debating Union",
    location: "Cape Town, South Africa",
    description: "A podcast about ideas that are genuinely difficult to argue against.",
  },
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "University of Waterloo Debating Society",
    location: "Waterloo, Canada",
    description: "Personal website: cybersecurity + debate + fun stuff.",
  },
  {
    name: "The Dispatch",
    url: "https://thedispatch.substack.com",
    type: "newsletter",
    club: "Oxford Union",
    location: "Oxford, United Kingdom",
    description: "Weekly takes on policy, philosophy, and competitive debate from a BP circuit veteran.",
  },
  {
    name: "Rebuttal Hour",
    url: "https://rebuttalhour.fm",
    type: "podcast",
    club: "Yale Debate Association",
    location: "New Haven, United States",
    description: "Long-form conversations with debaters, coaches, and adjudicators from across the circuit.",
  },
  {
    name: "Case Files",
    url: "https://casefiles.beehiiv.com",
    type: "newsletter",
    club: "Sydney Debating Union",
    location: "Sydney, Australia",
    description: "Motion breakdowns, case structures, and prep notes for BP and Worlds-style debate.",
  },
  {
    name: "Priya Nair",
    url: "https://priyanair.in",
    type: "website",
    club: "NLSIU Debate Club",
    location: "Bangalore, India",
    description: "Writing on law, rhetoric, and what competitive debate taught me about argument.",
  },
  {
    name: "The Flow",
    url: "https://youtube.com/@theflowdebate",
    type: "youtube",
    club: "McGill Debate Union",
    location: "Montreal, Canada",
    description: "Rounds, tutorials, and coaching breakdowns for new and experienced debaters.",
  },
  {
    name: "Finn Larsen",
    url: "https://finnlarsen.dk",
    type: "website",
    club: "Copenhagen Debate Society",
    location: "Copenhagen, Denmark",
    description: "Essays on European politics and the craft of persuasion.",
  },
  {
    name: "Threshold",
    url: "https://threshold.ghost.io",
    type: "newsletter",
    club: "Trinity College Dublin Philosophical Society",
    location: "Dublin, Ireland",
    description: "At the edge of policy and philosophy — one motion per issue, argued both ways.",
  },
  {
    name: "Aiko Tanaka",
    url: "https://aikotanaka.jp",
    type: "website",
    club: "Waseda University Debating Society",
    location: "Tokyo, Japan",
    description: "Notes on Asian BP circuit, judging philosophy, and life after competitive debate.",
  },
  {
    name: "Hard to Rebut",
    url: "https://hardtorebut.com",
    type: "podcast",
    club: "University of Cape Town Debating Union",
    location: "Cape Town, South Africa",
    description: "A podcast about ideas that are genuinely difficult to argue against.",
  },
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "University of Waterloo Debating Society",
    location: "Waterloo, Canada",
    description: "Personal website: cybersecurity + debate + fun stuff.",
  },
  {
    name: "The Dispatch",
    url: "https://thedispatch.substack.com",
    type: "newsletter",
    club: "Oxford Union",
    location: "Oxford, United Kingdom",
    description: "Weekly takes on policy, philosophy, and competitive debate from a BP circuit veteran.",
  },
  {
    name: "Rebuttal Hour",
    url: "https://rebuttalhour.fm",
    type: "podcast",
    club: "Yale Debate Association",
    location: "New Haven, United States",
    description: "Long-form conversations with debaters, coaches, and adjudicators from across the circuit.",
  },
  {
    name: "Case Files",
    url: "https://casefiles.beehiiv.com",
    type: "newsletter",
    club: "Sydney Debating Union",
    location: "Sydney, Australia",
    description: "Motion breakdowns, case structures, and prep notes for BP and Worlds-style debate.",
  },
  {
    name: "Priya Nair",
    url: "https://priyanair.in",
    type: "website",
    club: "NLSIU Debate Club",
    location: "Bangalore, India",
    description: "Writing on law, rhetoric, and what competitive debate taught me about argument.",
  },
  {
    name: "The Flow",
    url: "https://youtube.com/@theflowdebate",
    type: "youtube",
    club: "McGill Debate Union",
    location: "Montreal, Canada",
    description: "Rounds, tutorials, and coaching breakdowns for new and experienced debaters.",
  },
  {
    name: "Finn Larsen",
    url: "https://finnlarsen.dk",
    type: "website",
    club: "Copenhagen Debate Society",
    location: "Copenhagen, Denmark",
    description: "Essays on European politics and the craft of persuasion.",
  },
  {
    name: "Threshold",
    url: "https://threshold.ghost.io",
    type: "newsletter",
    club: "Trinity College Dublin Philosophical Society",
    location: "Dublin, Ireland",
    description: "At the edge of policy and philosophy — one motion per issue, argued both ways.",
  },
  {
    name: "Aiko Tanaka",
    url: "https://aikotanaka.jp",
    type: "website",
    club: "Waseda University Debating Society",
    location: "Tokyo, Japan",
    description: "Notes on Asian BP circuit, judging philosophy, and life after competitive debate.",
  },
  {
    name: "Hard to Rebut",
    url: "https://hardtorebut.com",
    type: "podcast",
    club: "University of Cape Town Debating Union",
    location: "Cape Town, South Africa",
    description: "A podcast about ideas that are genuinely difficult to argue against.",
  },
  {
    name: "Advait Sangle",
    url: "https://advaitsangle.com",
    type: "website",
    club: "University of Waterloo Debating Society",
    location: "Waterloo, Canada",
    description: "Personal website: cybersecurity + debate + fun stuff.",
  },
  {
    name: "The Dispatch",
    url: "https://thedispatch.substack.com",
    type: "newsletter",
    club: "Oxford Union",
    location: "Oxford, United Kingdom",
    description: "Weekly takes on policy, philosophy, and competitive debate from a BP circuit veteran.",
  },
  {
    name: "Rebuttal Hour",
    url: "https://rebuttalhour.fm",
    type: "podcast",
    club: "Yale Debate Association",
    location: "New Haven, United States",
    description: "Long-form conversations with debaters, coaches, and adjudicators from across the circuit.",
  },
  {
    name: "Case Files",
    url: "https://casefiles.beehiiv.com",
    type: "newsletter",
    club: "Sydney Debating Union",
    location: "Sydney, Australia",
    description: "Motion breakdowns, case structures, and prep notes for BP and Worlds-style debate.",
  },
  {
    name: "Priya Nair",
    url: "https://priyanair.in",
    type: "website",
    club: "NLSIU Debate Club",
    location: "Bangalore, India",
    description: "Writing on law, rhetoric, and what competitive debate taught me about argument.",
  },
  {
    name: "The Flow",
    url: "https://youtube.com/@theflowdebate",
    type: "youtube",
    club: "McGill Debate Union",
    location: "Montreal, Canada",
    description: "Rounds, tutorials, and coaching breakdowns for new and experienced debaters.",
  },
  {
    name: "Finn Larsen",
    url: "https://finnlarsen.dk",
    type: "website",
    club: "Copenhagen Debate Society",
    location: "Copenhagen, Denmark",
    description: "Essays on European politics and the craft of persuasion.",
  },
  {
    name: "Threshold",
    url: "https://threshold.ghost.io",
    type: "newsletter",
    club: "Trinity College Dublin Philosophical Society",
    location: "Dublin, Ireland",
    description: "At the edge of policy and philosophy — one motion per issue, argued both ways.",
  },
  {
    name: "Aiko Tanaka",
    url: "https://aikotanaka.jp",
    type: "website",
    club: "Waseda University Debating Society",
    location: "Tokyo, Japan",
    description: "Notes on Asian BP circuit, judging philosophy, and life after competitive debate.",
  },
  {
    name: "Hard to Rebut",
    url: "https://hardtorebut.com",
    type: "podcast",
    club: "University of Cape Town Debating Union",
    location: "Cape Town, South Africa",
    description: "A podcast about ideas that are genuinely difficult to argue against.",
  },
];
